export const ADD_ORDER_QUEUE_REQUEST = "ADD_ORDER_QUEUE_REQUEST";
export const ADD_ORDER_QUEUE_SUCCESS = "ADD_ORDER_QUEUE_SUCCESS";
export const ADD_ORDER_QUEUE_FAIL = "ADD_ORDER_QUEUE_FAIL";

export const GET_ORDER_STATUS_REQUEST = "GET_ORDER_STATUS_REQUEST";
export const GET_ORDER_STATUS_SUCCESS = "GET_ORDER_STATUS_SUCCESS";
export const GET_ORDER_STATUS_FAIL = "GET_ORDER_STATUS_FAIL";